INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Monstera Deliciosa', 
      15, 
      'The Monstera Deliciosa, also known as the Swiss Cheese Plant, is a popular tropical houseplant with large, glossy leaves that develop iconic splits and holes as they mature.', 
      25, 
      0, 
      '/images/_29b94ca3-a839-4192-b69c-d516b853f015.jpg', 
      'Tropical', 
      'Medium (2-3 feet)', 
      'Bright, indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Tradescantia zebrina (Wandering Jew)', 
      20, 
      'Tradescantia zebrina, also known as Wandering Jew or Inch Plant, is a vibrant and fast-growing trailing plant with striking purple and silver striped leaves. It thrives in bright indirect light and requires regular watering to keep its soil evenly moist.', 
      22, 
      0, 
      '/images/_49c95c5c-2477-4aee-a18c-65051f33d59b.jpg', 
      'Trailing Plants', 
      'Medium (6-12 inches)', 
      'Bright indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Fiddle Leaf Fig', 
      8, 
      'The Fiddle Leaf Fig is a popular indoor tree with large, glossy fiddle-shaped leaves. It makes a striking statement as a focal point in any room and prefers bright, indirect light.', 
      45, 
      0, 
      '/images/_bb6ce6d8-c399-4f48-a284-b7ee68ae9272.jpg', 
      'Tree', 
      'Medium to Tall (3-6 feet)', 
      'Bright, indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Caladium (Caladium bicolor)', 
      15, 
      'Caladium, particularly Caladium bicolor varieties, are tropical plants prized for their colorful and uniquely patterned arrow-shaped leaves. They thrive in indirect light and require consistently moist soil to maintain their vibrant appearance.', 
      20, 
      0, 
      '/images/_5087f0a1-2149-479a-b67c-9be23d416f60.jpg', 
      'Tropical Foliage', 
      'Medium (12-18 inches)', 
      'Indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'String of Pearls', 
      12, 
      'The String of Pearls is a unique and eye-catching succulent with trailing stems adorned with spherical, bead-like leaves. It''s an ideal choice for hanging baskets or elevated planters.', 
      20, 
      0, 
      '/images/_660d0190-e87c-4187-8f78-5f8da4d6c222.jpg', 
      'Succulent', 
      'Trailing (up to 1-2 feet)', 
      'Bright, indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Epipremnum aureum (Golden Pothos)', 
      20, 
      'Epipremnum aureum, also known as Golden Pothos or Devil''s Ivy, is a popular and versatile indoor plant with heart-shaped, glossy leaves marbled in green and yellow. It''s easy to care for and can thrive in various light conditions.', 
      18, 
      0, 
      '/images/_ddecc805-894e-427e-ad50-860c67d0d43e.jpg', 
      'Trailing Plants', 
      'Trailing (up to 6 feet)', 
      'Low to bright indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Fittonia spp. (Nerve Plant)', 
      15, 
      'Fittonia spp., also known as Nerve plants, are eye-catching indoor plants with vibrant, veined leaves that come in various colors like green, pink, and red. They thrive in medium to bright indirect light and require consistently moist soil to stay healthy.', 
      18, 
      0, 
      '/images/_4c4fb6dd-4e5d-4a3e-9853-1762f30be34a.jpg', 
      'Small Plants', 
      'Low (6-12 inches)', 
      'Medium to bright indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Calathea Orbifolia', 
      7, 
      'The Calathea Orbifolia is a stunning indoor plant known for its large, round leaves with silver-green stripes. It''s prized for its decorative foliage and prefers bright, indirect light.', 
      25, 
      0, 
      '/images/_3a1135a4-30fa-49af-a9eb-f75079249f7b.jpg', 
      'Decorative Foliage', 
      'Medium (1-2 feet)', 
      'Bright, indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Pilea Peperomioides', 
      10, 
      'The Pilea Peperomioides, also known as the Chinese Money Plant or Pancake Plant, is a charming and easy-to-care-for indoor plant characterized by its round, coin-shaped leaves on upright stems.', 
      12, 
      0, 
      '/images/_660b30c5-742b-4046-9779-97ec7be3466a.jpg', 
      'Small Plants', 
      'Small (6-12 inches)', 
      'Bright, indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Strelitzia reginae (Bird of Paradise)', 
      5, 
      'Strelitzia reginae, also known as Bird of Paradise, is a stunning tropical plant with large, banana-like leaves and striking orange and blue bird-shaped flowers. It thrives in bright indirect light and requires regular watering to keep its soil evenly moist during the growing season.', 
      45, 
      0, 
      '/images/_ba23f0cd-5a98-48cf-a9f4-567a9e553645.jpg', 
      'Tropical Plants', 
      'Large (4-6 feet)', 
      'Bright indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Calathea spp. (Calathea varieties)', 
      12, 
      'Calathea spp., including varieties like Calathea orbifolia and Calathea medallion, are beautiful and unique indoor plants known for their ornate and colorful foliage patterns. These plants prefer bright, indirect light and moderate humidity.', 
      30, 
      0, 
      '/images/_39b2dea7-f8ce-4b63-83f3-5d53f7c77eaf.jpg', 
      'Decorative Foliage', 
      'Small to Medium (1-2 feet)', 
      'Bright, indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Philodendron spp. (Various Types)', 
      18, 
      'Philodendron spp., including varieties like Philodendron Brasil and Philodendron Micans, are versatile and attractive indoor plants known for their lush foliage and easy-care nature. These plants thrive in medium to bright indirect light and are perfect for adding greenery to any space.', 
      20, 
      0, 
      '/images/_266c55cb-c99a-4654-acbf-4ba5c63f085a.jpg', 
      'Trailing Plants', 
      'Trailing (up to 4 feet)', 
      'Medium to bright indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Spider Plant (Chlorophytum comosum)', 
      25, 
      'The Spider Plant, scientifically known as Chlorophytum comosum, is a popular and easy-to-care-for indoor plant characterized by its arching, narrow leaves with white variegation. It''s known for its air-purifying properties and ability to produce ''spiderettes'' or baby plants on long, wiry stems.', 
      15, 
      0, 
      '/images/_75a93335-aac8-46f2-9cfe-be6efdf5774b.jpg', 
      'Trailing Plants', 
      'Trailing (up to 2 feet)', 
      'Moderate to bright indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Alocasia amazonica', 
      15, 
      'Alocasia amazonica, also known as African Mask Plant, is a stunning indoor plant featuring large, arrow-shaped leaves with prominent veins and striking dark green foliage contrasted by silver-white veins. It thrives in bright, indirect light and adds a dramatic touch to any indoor space.', 
      40, 
      0, 
      '/images/_8a6a2f3a-3cb0-4d5a-94d7-53cd14c3dbbe.jpg', 
      'Large Plants', 
      'Tall (2-3 feet)', 
      'Bright, indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Maranta leuconeura (Prayer Plant)', 
      20, 
      'Maranta leuconeura, also known as the Prayer Plant, is a captivating indoor plant with unique, patterned leaves that fold upward in the evening resembling hands in prayer. It thrives in low to moderate indirect light and requires consistent moisture.', 
      25, 
      0, 
      '/images/_38b2bc57-7824-4cde-a0ee-bde7c6ea7dd4.jpg', 
      'Decorative Foliage', 
      'Medium (1-2 feet)', 
      'Low to moderate indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Pothos (Epipremnum aureum varieties)', 
      25, 
      'Pothos (Epipremnum aureum) is a versatile and popular indoor plant known for its trailing vines and easy care. Varieties like Marble Queen and Neon feature variegated leaves that add color and interest to any space. Pothos plants thrive in low to moderate indirect light and require minimal maintenance.', 
      18, 
      0, 
      '/images/_2997f804-a24b-4b6c-8eb9-87a8edfaf148.jpg', 
      'Trailing Plants', 
      'Trailing (up to 6 feet)', 
      'Low to moderate indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Hoya carnosa (Wax Plant)', 
      15, 
      'Hoya carnosa, also known as the Wax Plant or Hindu Rope Plant, is a beautiful and unique indoor plant prized for its waxy, succulent leaves and clusters of star-shaped flowers. It thrives in bright indirect light and requires minimal care, making it an ideal choice for any indoor setting.', 
      30, 
      0, 
      '/images/_ba5b5709-3a51-408e-bca8-7f7a23d462e1.jpg', 
      'Succulents', 
      'Medium (1-2 feet)', 
      'Bright indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Peperomia obtusifolia (Baby Rubber Plant)', 
      15, 
      'Peperomia obtusifolia, also known as the Baby Rubber Plant, is a compact and attractive indoor plant with glossy, rounded leaves that have a rubbery texture. It''s easy to care for and thrives in moderate indoor light conditions, making it a perfect choice for tabletops or shelves.', 
      20, 
      0, 
      '/images/_aa79d1a7-3050-49c1-b999-83c3d0f058b9.jpg', 
      'Small Plants', 
      'Small (6-12 inches)', 
      'Moderate indoor light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Anthurium (Flamingo Flower)', 
      12, 
      'Anthurium, also known as Flamingo Flower or Laceleaf, is a stunning tropical plant prized for its glossy, heart-shaped leaves and vibrant, long-lasting flowers. It thrives in bright indirect light and requires regular watering to keep its soil consistently moist.', 
      35, 
      0, 
      '/images/_20997485-1f14-49b9-98fd-bbaa17f6c95d.jpg', 
      'Flowering Plants', 
      'Medium (1-2 feet)', 
      'Bright indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Dracaena marginata (Dragon Tree)', 
      15, 
      'Dracaena marginata, also known as the Dragon Tree, is a striking indoor plant with thin, upright stems and narrow, sword-shaped leaves that have a reddish edge. It''s an excellent air-purifying plant and can thrive in various light conditions.', 
      25, 
      0, 
      '/images/_6a7021c9-1c89-41db-99e3-7b5014fc6e15.jpg', 
      'Tall Plants', 
      'Tall (3-6 feet)', 
      'Moderate to bright indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Begonia rex (Rex Begonia)', 
      10, 
      'Begonia rex, also known as Rex Begonia, is a striking and colorful indoor plant prized for its ornamental foliage. It features large, textured leaves with intricate patterns in shades of green, silver, pink, and burgundy. Rex Begonias thrive in bright indirect light and require consistently moist soil.', 
      30, 
      0, 
      '/images/_b64a80f4-3a08-45ab-8da6-b8244c914bee.jpg', 
      'Decorative Foliage', 
      'Medium (8-12 inches)', 
      'Bright indirect light', 
      'Moderate', 
      1, 
      0, 
      1, 
      0
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Aspidistra elatior (Cast Iron Plant)', 
      8, 
      'Aspidistra elatior, also known as the Cast Iron Plant, is a hardy and low-maintenance indoor plant with dark green, leathery leaves. It''s well-suited for low-light conditions and can tolerate neglect, earning its nickname as the ''Cast Iron'' plant. Perfect for adding greenery to dim corners.', 
      25, 
      0, 
      '/images/_69f3daff-a412-4eb8-aea4-86c89674a614.jpg', 
      'Low-Light Plants', 
      'Medium (12-24 inches)', 
      'Low to moderate indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Aloe Vera', 
      15, 
      'Aloe Vera is a popular succulent known for its medicinal properties. It has thick, fleshy leaves that contain a gel with various health benefits.', 
      10, 
      0, 
      '/images/_1a16d159-4cf5-4c7a-9291-bf8772482b23.jpg', 
      'Succulent', 
      'Small to Medium (1-2 feet)', 
      'Bright, indirect light', 
      'Easy', 
      1, 
      1, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Parlor Palm', 
      12, 
      'The Parlor Palm, also known as Chamaedorea elegans, is a classic indoor palm plant with feathery, arching fronds. It''s well-suited for low light conditions and adds a tropical touch to any space.', 
      30, 
      0, 
      '/images/_190d30ce-4f0a-49db-8637-dd1e0dc156f5.jpg', 
      'Palm', 
      'Medium (2-4 feet)', 
      'Low to moderate indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Tradescantia spathacea (Moses-in-the-cradle)', 
      12, 
      'Tradescantia spathacea, also known as Moses-in-the-cradle or Boat Lily, is an attractive and low-maintenance tropical plant with glossy, dark green leaves and contrasting purple undersides. It produces small white flowers nestled in boat-shaped bracts. This plant thrives in bright indirect light and requires regular watering.', 
      22, 
      0, 
      '/images/_58f6530b-0482-41f1-a9b3-3e7701f7dc51.jpg', 
      'Tropical Foliage', 
      'Medium (12-18 inches)', 
      'Bright indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Syngonium podophyllum (Arrowhead Plant)', 
      20, 
      'Syngonium podophyllum, also known as Arrowhead Plant or Arrowhead Vine, is a versatile and easy-to-care-for indoor plant with arrow-shaped leaves that vary in color and pattern. It thrives in indirect light and prefers consistently moist soil. This plant is perfect for hanging baskets or as a trailing plant.', 
      18, 
      0, 
      '/images/_86ce692c-f269-4fc1-bfb1-ac6b754f8219.jpg', 
      'Trailing Plants', 
      'Medium (12-18 inches)', 
      'Indirect light', 
      'Easy', 
      1, 
      0, 
      1, 
      1
    );
INSERT INTO Products (name, quantity_in_stock, description, price, rating, image_url, category, height, light_requirements, care_difficulty, indoor, outdoor, air_purifying, pet_friendly) VALUES (
      'Snake Plant', 
      20, 
      'The Snake Plant, also known as Sansevieria, is a hardy and low-maintenance indoor plant with upright, sword-like leaves. It thrives in various light conditions and is known for its air-purifying properties.', 
      15, 
      0, 
      '/images/_db6e0d44-7efe-4568-9dce-dd83ef3fa025.jpg', 
      'Low Maintenance', 
      'Small to Medium (1-3 feet)', 
      'Low to bright indirect light', 
      'Very Easy', 
      1, 
      0, 
      1, 
      1
    );